### ISSUE TITLE
Problem with AbstractPlaces inheritance

### ISSUE THREAD

**Issue by richardreeve** [EcoJulia/EcoBase.jl#11]
We discussed this in #8 and hoped we had resolved it, but unfortunately we now have real problems with this inheritance structure:
```julia
abstract type AbstractPlaces end

abstract type AbstractLocations <: AbstractPlaces end

abstract type AbstractGrid end
```
We have a lot more information stored in our `AbstractPlaces` subtype, `AbstractPartition`, which generally has no location information, but can do, say for @claireh93's work. Unfortunately we can't inherit from `AbstractPartition` and `AbstractLocations` even though she does have a `AbstractGrid` object that allows her to do her plotting. I think what we need is:

```julia
abstract type AbstractPlaces end

abstract type AbstractLocations end

abstract type AbstractGrid <: AbstractLocations end
```
with the `AbstractPlaces` subtype containing an object that contains the location information (or not, depending, obviously) rather than the `AbstractLocations` subtype definitely having it. That would solve our inheritance problems and mean that when we release Claire's code (and/or expand `Metacommunity` to formally handle locations) it would all work. Would that cause difficulties for you?

**Comment by mkborregaard** [comment]
I'm trying to understand exactly what the problem is and why this would help? It would mean reimplementing the structure in SpatialEcology so I'd like to understand why. Are we thinking differently about these types?

**Comment by richardreeve** [comment]
It's just changing which is the container, and which is inherited, so not thinking terribly differently about things, no, but the implication is that AbstractLocations can respond directly to questions about locations, but AbstractGrid can do it in a more specific way (at least that's how I see it affecting you conceptually). The problem for us is that we inherit directly from AbstractPlaces, and since multiple inheritance doesn't exist (and in any case is always a nightmare in my experience with these incestuous common-supertype relationships), we can't also inherit from AbstractLocations. Since we often are not dealing with real locations, we can't choose to inherit from AbstractLocations instead, and that means we just have to ditch AbstractLocations inheritance, which will break some interface expectations I imagine when we really are dealing with locations. Instead we will have our own location-analog, which contains an AbstractGrid anyway...

**Comment by mkborregaard** [comment]
But just to understand - doesn't having a parametric `AbstractLocations{<:AbstractGrid}` type resolve that? That's the intention of the current type hierarchy IIRC.

**Comment by richardreeve** [comment]
It would if we could inherit from it, but we can’t as far as I can see (I’m open to suggestions!)... because we don’t always have a location, we have to inherit from AbstractPlaces instead, and so to have the possibility of a location, we need AbstractPlaces{AbstractLocation} or AbstractPlaces{AbstractGrid} depending on whether we have points or a regular grid (or indeed AbstractPlaces{Vector{String}} or something for non-location-based data).

**Comment by richardreeve** [comment]
I've actually identified another solution, which is essentially a deeper integration of my type hierarchy with EcoBase. If I get rid of AbstractPartition entirely and use AbstractPlaces instead, then some partition types can inherit from AbstractPlaces and some from AbstractLocations. I would probably do the same for AbstractThings if I did that, and it would be moderately disruptive in that there are about 150 places where I refer to one of these types, some of which where I am referring to them to distinguish between any EcoBase-derived type and one specifically in my hierarchy.

Doing that wouldn't be entirely bad news obviously(!), but I guess it would be good to really understand why/whether the existing inheritance mechanism is the right one first, as tbh I never really understood why it was the best option in the first place (except perhaps that it was the structure that your code already had?).

**Comment by mkborregaard** [comment]
I wrote "if you convince me it's better" but I meant of course "if we decide it's better" :joy: :-p

**Comment by richardreeve** [comment]
Okay. Maybe it's helpful if I say something very similar about the other type structure:

Places are the areas where species are. They can be test tubes, grid cells, simulated communities, actual sites or whatever.
Locations *represent the* ~are a type of place that have a~ geographical component *of the places*. They are characterized by ~two things:~ their position in space (spatial coordinates), ~and~ *while places contain* their other metadata. ~It's essentially the same concept as a SpatialData.frame in R or a GeoDataframe in Julia (GeoStats package), etc.~
Grids are a certain type of position in space - defining the situation where the position is an index into a regular grid. *As such they are simply a subtype of locations.*

Now I'm faced with the conflict between the existing structure and our geographically-based data, and how it turns out we've represented it, I'm not sure why it makes sense for locations to hold metadata and geographical data unless you're on a grid in which case the geographical data is held in a grid object rather than metadata in one object and spatial data in another, which is a specialised object if the spatial data is on a grid... I also can't stress enough that I don't know anything about spatial data in R or Julia, but do GeoDataframes and SpatialData.frames hold grids as separate objects but point data in the data frames?

The fact that EcoBase's type structure is incompatible with Diversity's wrt spatial data is almost a side issue, though it sounds like it will be somewhat aggravating for either of us to fix.

**Comment by mkborregaard** [comment]
I'm not really sure I understand the middle paragraph :-) But yes, in R you have SpatialPointsDataFrame and SpatialGridDataFrame, corresponding, I'd say, to our `Location{PointData}` and `Location{GridData}`:
```r
> class(mygrid)
[1] "SpatialGridDataFrame"
attr(,"package")
[1] "sp"
> slotNames(mygrid)
[1] "data"        "grid"        "bbox"       
[4] "proj4string"
> mygrid@grid
                       x      y
cellcentre.offset 178460 329620
cellsize              40     40
cells.dim             78    104
> class(mygrid@data)
[1] "data.frame"
> class(mypoints)
[1] "SpatialPointsDataFrame"
attr(,"package")
[1] "sp"
> slotNames(mypoints)
[1] "data"        "coords.nrs"  "coords"     
[4] "bbox"        "proj4string"
> class(mypoints@coords)
[1] "matrix"
> dim(mypoints@coords)
[1] 155   2
```

**Comment by richardreeve** [comment]
I was just tracking changes to your paragraph to get from your type hierarchy to mine. Maybe it's easier if I just write it out in full:

*Places are the areas where species are. They can be test tubes, grid cells, simulated communities, actual sites or whatever.
Locations represent the geographical component of the places. They are characterized by  their position in space (spatial coordinates), while places contain their other metadata.
Grids are a certain type of position in space - defining the situation where the position is an index into a regular grid. As such they are simply a subtype of locations.*

Anyway, now I realise you have a `PointData` type too, it seems to me that `Location` in `Location{PointData}` and `Location{GridData}` just holds the metadata while it contains the spatial info in a separate object. That's all AbstractPlaces is anyway, so there's no reason why it shouldn't be `Place{PointData}` and `Place{GridData}`. If `PointData <: LocationData` and `GridData <: LocationData`, then we can just say that it's a location type if it's `<: AbstractPlaces{<: LocationData}`, with `<: AbstractPlaces{GridData}` being equivalent to `SpatialGridDataFrame` and `<: AbstractPlaces{PointData}` being equivalent to `SpatialPointsDataFrame`. The default supertype for non-location data would probably be `<: AbstractPlaces{Nothing}`... does that make sense?

**Comment by richardreeve** [comment]
You’re obviously right, but my feeling was (a) the first package in EcoJulia was a spatial package(!), but (b) more generally a lot of ecology relates to location or space in some sense, so treating it slightly differently is probably okay - also there are some pretty standard ways of recording spatial info, so it would be nice to be able to represent them.

Generally, a `has_location()` trait would definitely be a good thing to have though, but also trivial to implement with what we have here:

```julia
has_location(::AbstractPlaces) = false
has_location(::AbstractPlaces{<: AbstractLocationData}) = true
```

The second thing that could have a kind of privileged place in EcoBase would be species or taxonomic information, though we haven’t discussed that yet. A third would be time or dates. I can’t think of anything else. 

PS Once traits are formally part of the language and so multiple inheritance is possible via Java-like interfaces (that is happening at some point, right, I didn’t just imagine it?), then I think using just traits for all of this would be great, but for the time being we can only dispatch on types...

**Comment by mkborregaard** [comment]
> I haven't really followed this in terms of implementation details, but philosophically, isn't spatial information just another type of metadatum?

So, in a sense everything is just (meta)data. In principle, all of SpatialEcology could be represented as a relational database with linked tables and all calls be translated to SQL behind the scenes. It might even be faster than the current implementation. But what we want to do is to have some types that represent what they are, to make coding more intuitive. So IMHO, we should have species information, site/place information, spatial and possibly temporal information special-cased.

Another reason for having the type of spatial data appear in the type signature is type stability. Say you extract variables from an object with `GridData` into a spatial object (as currently done by the plotting methods), that would result in a Raster file. But for `PointData` it would be a point Shapefile. I'm not sure about what the future will be with traits, but currently `has_location` leads to runtime dispatch.

> The default supertype for non-location data would probably be `<: AbstractPlaces{Nothing}`

Yes that could work I guess, parametric types are just another way of expressing inheritance of course.  In fact that is essentially what I had before we did EcoBase. It might still be some refactoring for me, but that's not what is important here, which is to make the right implementation.

Let me just throw an extra consideration in here: what if some other package in the future wants to use EcoBase but wants to store his `MyType <: AbstractPlaces{T}` using a GeoDataframe (if that type catches on - what would `T` then be? I guess that is solvable under this scenario.

Finally @richardreeve I do think it would be nice if the format we end with could be integrated more deeply in Diversity. What stops `AbstractPartition` from being replaced by `AbstractPlaces`? What design would support that best?

Somewhat related - @kescobo could you make me a collaborator on MicroBiome? I'll run your tests and update every time I do something in SpatialEcology that breaks it. Promise I'll not merge anything else :-) .

**Comment by richardreeve** [comment]
Yes, @mkborregaard, you're right. The parametric type hierarchy I'm now proposing is just another type of inheritance, but the important issues for me are the three you've identified: (a) avoiding runtime dispatch, (b) compatibility with all of our (lightly modified!) codebases and (c) respecting the fact that this is a base for ecology, and so allowing some specific stuff that useful for us! What we're describing here will satisfy all of this I think. And I'm confident it would allow me to drop AbstractPartition and use AbstractPlaces as the supertype for my partitioning - I'm having a go at that now - the big problem is how many methods I define on AbstractPartitions that would now bleed through to your code in potentially unhelpful ways.

Looking incredibly briefly at GeoDataFrame, I might just put that as the parameterised type, with an AbstractPlaces subclass that is just a shim that holds it and passes on requests about the spatial and other metadata to it?

Anyway, I've updated #12 to reflect the changes we're discussing.

Incidentally, I would be happy to add a parametric extension at the same time for AbstractThings, which optionally refers to the type of species information present... I don't think we're ready to think about what we're going to do about

**Comment by mkborregaard** [comment]
Great, I'll have a  look at adapting SpatialEcology (and Microbiome) to #12. 

I don't honestly know anything about GeoDataFrame, just that it exists. There are even two different implementations of it. The obvious right people to ask are "yeesian" and "visr", they run the Geo org (juliohm who has GeoDataframes is a geologist so I think the Geo is for geology but not sure).

FWIW I've pushed an extra abstract type for all EcoBase types at the top of SpatialEcology called SELocations, SEThings etc., to have an abstract interface that doesn't leak out. We could talk about pushing functions on AbstractPlaces and AbstractThings up to EcoBase so they benefit all? (Strictly speaking, defining methods on EcoBase types in SpatialEcology or Diversity for functions that are not defined in either of these two packages is the definition of type piracy :-) ).

**Comment by mkborregaard** [comment]
While going through SpatialEcology I'll revisit that all methods are defined to the right place in the abstract hierarchy (as high as possible but no higher)
